# Generated by Django 4.2 on 2023-10-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='', max_length=100),
        ),
    ]
